# Generated by Django 2.1.4 on 2018-12-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='no',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
