# Generated by Django 2.1.4 on 2018-12-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt', '0003_auto_20181217_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='aid',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
