# Generated by Django 2.1.4 on 2018-12-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt', '0004_auto_20181217_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='aid',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tid',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
    ]
