# Generated by Django 2.1.4 on 2018-12-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt', '0009_auto_20181217_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='rating',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userreceivetran',
            name='value',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersendtran',
            name='value',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
